Gradesheet/urls.py
from django.contrib import admin
from django.urls import path, include
from UserAuth import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("UserAuth.urls", namespace="UserAuth")),
    path("admission/", include("admission.urls", namespace="admission")),
    path("", include("home.urls", namespace="home")),
    path("", include("course.urls", namespace="course")),
]

UserAuth/urls.py
from django.urls import path
from . import views


app_name="UserAuth"
urlpatterns = [
    path("login/",views.CustomLoginView.as_view(),name="login"),
    path("",views.CustomLoginView.as_view()),
    path("signup/",views.SignupView.as_view(),name="signup"),

    # path("",views.trial,name="trial")
]

home/urls.py
from django.urls import path

from home import api_views
from . import views
from UserAuth.views import LogoutView

app_name = "home"
urlpatterns = [
    path("home", views.home, name="home"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("api/home", api_views.HomeAPIView.as_view(), name="api-home"),
]

UserAuth/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Login(models.Model):
    email=models.EmailField(_("Email Address"), max_length=254,null=True)
    username=models.CharField(max_length=50)
    password=models.CharField(max_length=50)

UserAuth/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext_lazy as _
from admission.models import ParentsInfo, UserAdmission
from admission.teachers_model import TeachersInfoModel
from customUser.models import User
from customUser.admin import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def clean_email(self):
        email = self.cleaned_data["email"]
        # print(bool(UserAdmission.objects.get(parents_info__email=email)))
        try:
            UserAdmission.objects.get(student_info__email=email)
            return email
        except:
            try:
                ParentsInfo.objects.get(email=email)
                return email
            except:
                try:
                    TeachersInfoModel.objects.get(email=email)
                    return email
                except:
                    raise forms.ValidationError(
                        "Only the admitted student or Parents or the Teacher can create their accounts"
                    )


class LoginForm(forms.ModelForm):
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "password")


class MyForm(forms.Form):
    name = forms.CharField(label="Name", max_length=120, required=False)

UserAuth/views.py
from django.http.response import HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView
from UserAuth.forms import LoginForm
from customUser.models import User
from admission.models import ParentsInfo, UserAdmission
from admission.teachers_model import TeachersInfoModel
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy


class CustomLoginView(LoginView):
    template_name = "UserAuth/login.html"
    redirect_authenticated_user = True
    extra_context = {"title": "Login Form", "header": "Login", "form": LoginForm}

    def form_valid(self, form):
        return super().form_valid(form)


class SignupView(CreateView):
    template_name = "UserAuth/login.html"
    form_class = CustomUserCreationForm
    success_url = "/login"

    def is_teacher(self, query, email):
        try:
            admissionInfo = query.objects.get(email=email)
            return {"query": admissionInfo, "value": True}
        except:
            return {"query": "", "value": False}

    def is_student(self, query, email):
        try:
            admissionInfo = query.objects.get(student_info__email=email)
            return {"query": admissionInfo, "value": True}
        except:
            return {"query": "", "value": False}

    def is_parents(self, query, email):
        try:
            admissionInfo = query.objects.get(email=email)
            return {"query": admissionInfo, "value": True}
        except:
            return {"query": "", "value": False}

    def form_valid(self, form):
        """If the form is valid, save the associated model."""

        email = form.cleaned_data["email"]
        self.object = form.save()
        user = User.objects.get(email=email)
        is_student = self.is_student(UserAdmission, email)
        is_parents = self.is_parents(ParentsInfo, email)
        is_teacher = self.is_teacher(TeachersInfoModel, email)

        if is_parents["value"]:
            admissionInfo = is_parents["query"]
            user.role = "Parents"
            user.first_name = admissionInfo.f_name
            user.last_name = admissionInfo.l_name
            user.save()

        elif is_student["value"]:
            admissionInfo = is_student["query"]
            user.first_name = admissionInfo.basic_info.f_name
            user.last_name = admissionInfo.basic_info.l_name
            user.date_of_birth = admissionInfo.basic_info.date_of_birth
            user.save()

        elif is_teacher["value"]:
            admissionInfo = is_teacher["query"]
            user.role = "Teacher"
            user.first_name = admissionInfo.f_name
            user.last_name = admissionInfo.l_name
            user.username = admissionInfo.short_name
            user.save()

        return HttpResponseRedirect(self.get_success_url())


class CustomLogoutView(LogoutView):
    template_name = "UserAuth:login"

UserAuth/templates/UserAuth/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href= {% static 'UserAuth/base.css' %}>
    <link rel="stylesheet" href= {% static 'UserAuth/navbar.css' %}>
    {% block css %}{% endblock css %}
</head>
<body>
    {% include 'UserAuth/navbar.html' %}
    {% block body %}
    {% endblock body %}
</body>
</html>

UserAuth/templates/UserAuth/login.html
{% extends 'UserAuth/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock title %}
{% block css %}
<link rel="stylesheet" href={% static 'UserAuth/login.css' %}>
{% endblock css %}
  </head>
  {% block body %}
  <section class="login_form">
    <form method="post">
      {% csrf_token %}
      <header>
        <h1>
          {{header}}
        </h1></header>
      <table>
        {{form.as_table}}
      </table>
      <div><button type="submit" class="btn btn-submit">Submit</button></div>
    </form>
  </section>
{% endblock body %}
</html>

UserAuth/templates/UserAuth/navbar.html
{% block navbar %}<nav class="nav-container">
    <div class="logo">
        LOGO
    </div>
    <div class="menus">
        <ul class="list-container text-dec_none">
            {%if user.is_authenticated%}
                <li><a href="{% url 'home:home'%}">Home</a></li>
                <li><a href={% url 'home:logout' %}>Logout</a></li>
                <li><a href="/admin">Admin</a></li>
            {%else%}
                <li><a href="{% url 'UserAuth:login'%}">Login</a></li>  
            <li><a href=" {% url 'UserAuth:signup' %} ">Signup</a></li>
            {%endif%}
        </ul>
    </div>
</nav>
{% endblock navbar %}

UserAuth/templates/UserAuth/success_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Url</title>
</head>
<body>
    <h1>File Posted Successfully</h1>
</body>
</html>

UserAuth/templates/UserAuth/try.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trial</title>
</head>
<body>
    <form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">
    Submit
    </button>
    </form>
</body>
</html>